version: '3.9'

networks:
    backend-user:
    backend-task:
    frontend:

services:
  userdb:
    container_name: user-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=m153cur3p@55
    networks:
      - backend-user
    ports:
      - 8001:1433

  userapi:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    networks:
      - backend-user
      - frontend
    ports:
      - 8002:8080
    environment:
      - DB_HOST=userdb
      - DB_NAME=dms_user
      - DB_SA_PASSWORD=m153cur3p@55

  taskdb:
    container_name: task-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=m153cur3p@55
    networks:
      - backend-task
    ports:
      - 8003:1433

  taskapi:
    container_name: task-api
    image: ${DOCKER_REGISTRY-}taskapi
    build:
      context: .
      dockerfile: TaskAPI/Dockerfile
    networks:
      - backend-task
      - frontend
    ports:
      - 8004:8082
    environment:
      - DB_HOST=taskdb
      - DB_NAME=dms_task
      - DB_SA_PASSWORD=m153cur3p@55

  tasktrackerwebapp:
    image: ${DOCKER_REGISTRY-}tasktrackerwebapp
    build:
      context: .
      dockerfile: TaskTrackerWebApp/Dockerfile
    networks:
      - frontend
    ports:
      - 8005:80
    environment:
      - USER_API_HOST=userapi:8080
      - TASK_API_HOST=taskapi:8082

